// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRyl_K2OiGk2KJQxh-n7vRqGIz0tKc4Y8',
    appId: '1:85974797022:web:74352fbdef12b1f4af104f',
    messagingSenderId: '85974797022',
    projectId: 'gym-workout-tracker-6226c',
    authDomain: 'gym-workout-tracker-6226c.firebaseapp.com',
    storageBucket: 'gym-workout-tracker-6226c.appspot.com',
    measurementId: 'G-3JJ9LDKDY4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHs9KcXDy2Gq46iS9zTbTCEEqJKe_h1T0',
    appId: '1:85974797022:android:b786e0e70d364299af104f',
    messagingSenderId: '85974797022',
    projectId: 'gym-workout-tracker-6226c',
    storageBucket: 'gym-workout-tracker-6226c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByHP87M0SXu-8HGXfaRh3dWZUFAWGAeLQ',
    appId: '1:85974797022:ios:706985750254afa7af104f',
    messagingSenderId: '85974797022',
    projectId: 'gym-workout-tracker-6226c',
    storageBucket: 'gym-workout-tracker-6226c.appspot.com',
    iosClientId: '85974797022-pmdg6q1fgi6ovdgoeoudep0s2g97s7pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymWorkoutApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByHP87M0SXu-8HGXfaRh3dWZUFAWGAeLQ',
    appId: '1:85974797022:ios:706985750254afa7af104f',
    messagingSenderId: '85974797022',
    projectId: 'gym-workout-tracker-6226c',
    storageBucket: 'gym-workout-tracker-6226c.appspot.com',
    iosClientId: '85974797022-pmdg6q1fgi6ovdgoeoudep0s2g97s7pm.apps.googleusercontent.com',
    iosBundleId: 'com.example.gymWorkoutApp',
  );
}
